name: hydrosar
channels:
  - conda-forge
dependencies:
  - affine
  - asf_search
  - astropy
  - earthengine-api
  - gdal
  - geoglows
  - geopandas
  - geoviews
  - google-api-python-client
  - hvplot
  - hyp3_sdk
  - ipyfilechooser
  - ipympl==0.8.8
  - jupyter
  - kernda
  - matplotlib
  - mgrs
  - numpy
  - oauth2client
  - opensarlab_lib
  - pandas
  - pip
  - pykrige
  - pyproj
  - pysheds
  - python>=3.9
  - rasterio
  - rioxarray
  - s3fs
  - scikit-fuzzy
  - scipy<1.9
  - shapely
  - traitlets==5.1.1
  - pip:
    - fiona
    - url-widget
