name: Static analysis

on: push

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.8.2
    with:
      local_package_names: hydrosar
      excludes: notebooks/           # comma-separated list of glob patterns to exclude from checks

  call-secrets-analysis-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.8.2
