name: Static analysis

on: push

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.11.0
    with:
      local_package_names: hydrosar
      # comma-separated list of glob patterns to exclude from checks
      excludes: notebooks/,CCD30/
