name: Static analysis

on: push

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.8.2
    with:
      local_package_names: hydrosar
      # comma-separated list of glob patterns to exclude from checks
      excludes: notebooks/,CCD30/
