name: Tag version

on:
  push:
    branches:
      - main

jobs:
  call-bump-version-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.8.2
    with:
      user: fjmeyer
      email: fjmeyer@alaska.edu
    secrets:
      USER_TOKEN: ${{ secrets.HYDROSAR_RELEASE_TOKEN }}
